# Generated by Django 4.2.3 on 2023-11-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='createlist',
            new_name='usercreate',
        ),
    ]
