# Generated by Django 4.2.3 on 2023-11-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='usercreate',
            new_name='create_user',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='is_native',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='listing',
            name='imgurls',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
